### ISSUE TITLE
Static Routes

### ISSUE THREAD

**Issue by ghost** [laboratorio-a/FitMeApp#2]
Volendo ridefinire delle static routes arbitrarie, sembra che delle direttive più generali stiano sovrascrivendo le mie dichiarazioni (volevo evitare di duplicare dei css già presenti in node_modules, puntandoli direttamente lì). Potrebbe essere per la configurazione di yarn?

**Comment by matteo-laboratorio-a** [comment]
Hai ancora questo problema? Non mi è chiaro cosa intendi con static route...

**Comment by DjEmet** [comment]
```
// TODO: Path statica per attingere direttamente da node_modules
// per evitando duplicati - non funziona. Forse sovrascritta, Verificare.

// app.use('jquery-mobile',
// express.static(__dirname + '/node-modules/jquery-mobile/dist/'));
```

No, chiarendo la questione librerie non mi serve più questo. A meno di doverla includere fisicamente nel progetto in produzione.

**Comment by matteo-laboratorio-a** [comment]
Non credo che servirà, nel caso vediamo
